public enum ViewTypeId
{
    Unknown,
    CircleUfo,
    Square,
    TriangleShip,
    CircleContainer,
    OldConnector,
    OldCargo,
    FlameCircle,
    FireAura,
    Shield,
    SmallNebula,
    FireAuraBonus,
    ShieldBonus,
    DefaultPlasma,
    MediumPlasma,
    DefaultTurret,
    MediumTurret,
    DefaultLaserBeam
}